### PR TITLE
Attempt to copy input crs to output crs for slope algorithm

### PR DESCRIPTION
**Pull request by nyalldawson**
@jvdkwast can you give this branch a test? It should implement crs copying from source -> destination for just the SLOPE algorithm alone.

### CODE REVIEW

**Comment by jvdkwast** [comment]
It creates the aux.xml file.
However, the content is not the same as the original and lacks the CRS info.
What I did: 
1. Convert a projected dem.tif file to PCRaster format using the Convert to PCRaster Format tool. That creates this aux.xml file with projection info (EPSG: 32632):
[dem.map.aux.xml.zip](https://github.com/jvdkwast/qgis-processing-pcraster/files/7136029/dem.map.aux.xml.zip)
2. Calculate slope with the Slope tool. That runs without error and produces the slope map and aux.xml file:
[slope.map.aux.xml.zip](https://github.com/jvdkwast/qgis-processing-pcraster/files/7136043/slope.map.aux.xml.zip)
The xml doesn't contain the CRS info like the original one. The result layer in the Layers panel shows a question mark.
Here's the log:
[log.txt](https://github.com/jvdkwast/qgis-processing-pcraster/files/7136052/log.txt)

**Comment by jvdkwast** [comment]
@nyalldawson In addition to the above, gdal_edit.bat is not available in conda.

**Comment by nyalldawson** [comment]
@jvdkwast can you retest the latest changes in this branch? I'm trying a different approach now...

**Comment by jvdkwast** [comment]
I've downloaded the plugin from your set_crs branch. This version doesn't create the xml file. Tested on QGIS 3.16 Windows and 3.18 via Conda on Windows.

**Comment by nyalldawson** [comment]
Is there anything in the processing log?

**Comment by jvdkwast** [comment]
No, it just runs without error. How can I check that this is the updated version? 
[log.txt](https://github.com/jvdkwast/qgis-processing-pcraster/files/7209847/log.txt)

I see the old logo (R), so not sure if this is the right one that I downloaded from https://github.com/nyalldawson/qgis-processing-pcraster/tree/set_crs

**Comment by nyalldawson** [comment]
Hmm I don't think that's the right version -- if it fails you should get a explanatory message in the log. We could try merging this and then you could retest the master branch?

**Comment by jvdkwast** [comment]
Let's try. I can test it again after 1 hour.

**Comment by jvdkwast** [comment]
It works. Tested on both conda and Windows original.

**Comment by nyalldawson** [comment]
@jvdkwast great! So the only missing part now is that all the other (non slope) algorithms need the new line added to set the crs. Are you able to add this?

**Comment by nyalldawson** [comment]
Specifically this:

```
self.set_output_crs(output_file=outputFilePath, crs=input_dem.crs(), feedback=feedback, context=context)
```

But it'll need to be done for all the outputs from each algorithm, with the correct associated input layer crs specified

**Comment by jvdkwast** [comment]
Sure. I'll do that.

**Comment by jvdkwast** [comment]
Done

**Pull request merged**
