### PR TITLE
Base class method for generating PCRaster manual URLs

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by jvdkwast — APPROVED** [review]
I'll update the shortHelpString for all algorithms after you merge #44

**Comment by jvdkwast** [comment]
@OliverSchmitz will check if PCRaster can have fixed URL for the latest release documentation. I'll wait for an update on that.

**Comment by OliverSchmitz** [comment]
should work now by using latest instead of a version number, e.g.
https://pcraster.geo.uu.nl/pcraster/latest/documentation/pcraster_manual/sphinx/op_abs.html

**Comment by jvdkwast** [comment]
@OliverSchmitz Great! I'll update the scripts.

**Pull request merged**
